name: Build UCKG Docker Container

on: workflow_dispatch

jobs:
  run-ci-workflow:
    name: Run CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Verify Checkout worked
        run: |
          ls -a

      - name: Build docker image
        id: build-docker-image
        run: |
          docker build -t uckg-image:123 .
          docker save -o docker-image.tar uckg-image:123
          # Archive the Docker image as an artifact
          # if [[ -f "docker-image.tar" ]]; then
          #   mv docker-image.tar $GITHUB_WORKSPACE/docker-image.tar
          # fi
          echo "::set-output name=image_path::$GITHUB_WORKSPACE/docker-image.tar"

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ steps.build-docker-image.outputs.image_path }}
  